const settings = require('../settings');
const { AIRich } = require('../lib/messageBuilder');

async function aiCommand(sock, from, msg, isAdmin, session, args) {
    if (!isAdmin) {
        const builder = AIRich.warning(sock, settings.botName, 'Only owner can use this command.', 'AI command');
        return builder.send(from, { quoted: msg });
    }

    const action = args[0]?.toLowerCase();
    if (action === 'on') {
        session.aiEnabled = true;
        const builder = AIRich.success(sock, settings.botName, 'AI Auto-Reply Enabled!', 'AI settings');
        return builder.send(from, { quoted: msg });
    }

    if (action === 'off') {
        session.aiEnabled = false;
        const builder = AIRich.warning(sock, settings.botName, 'AI Auto-Reply Disabled!', 'AI settings');
        return builder.send(from, { quoted: msg });
    }

    if (args.length > 0) {
        const query = args.join(' ');
        try {
            await sock.sendMessage(from, { react: { text: '🤖', key: msg.key } });
            const response = await session.getAIResponse(from, query);
            const builder = AIRich.createBotCard(sock, {
                title: settings.botName,
                body: 'AI response',
                footer: 'Generated by AI',
                lines: [response],
                items: [
                    { label: 'Prompt', value: query },
                    { label: 'Status', value: 'Completed' },
                ],
            });
            return builder.send(from, { quoted: msg });
        } catch (e) {
            const builder = AIRich.error(sock, settings.botName, `AI Error: ${e.message}`, 'AI command');
            return builder.send(from, { quoted: msg });
        }
    }

    const builder = AIRich.warning(sock, settings.botName, 'Usage:\n.ai [on/off] - Toggle Auto-Reply\n.ai [query] - Ask AI something', 'AI command');
    return builder.send(from, { quoted: msg });
}

module.exports = aiCommand;
